name: project
version: 1.2.3
description: >-
  Have you been turned into a newt?  Would you like to be?
  This package can help. It has all of the
  newt-transmogrification functionality you have been looking
  for.
homepage: rwietter.dev
documentation: rwietter.dev
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dev_dependencies:
  test: '>=1.15.0 <2.0.0'
dependencies:
  http: ^0.13.0